package com.company.platform.audit;

public enum AuditEventType {
    OTP_REQUESTED,
    OTP_DELIVERY_FAILED,
    OTP_VERIFICATION_FAILED,
    OTP_ATTEMPTS_EXCEEDED,
    USER_REGISTERED,
    LOGIN_SUCCEEDED,
    LOGIN_REJECTED_INACTIVE_ACCOUNT,
    TOKEN_REFRESHED,
    REFRESH_TOKEN_REUSE_DETECTED,
    LOGOUT,
    LOGOUT_ALL_SESSIONS
}
